"""
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
"""

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        s_list = sorted(list(s))
        t_list = sorted(list(t))

        for s_char in s_list:
            t_list.remove(s_char)
        return t_list[0]
    
    
# 다른 풀이
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        for y in t:
            if t.count(y) > s.count(y):
                return y